services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./content:/app/content
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development